-- ============================================================
-- Securing the Context Store
-- Anonymization, Masking, and PII Protection on SAP HANA Cloud
-- Companion script
-- ============================================================
--
-- WHAT THIS SCRIPT DOES
-- ---------------------
-- An enterprise RAG context store holds sensitive business content
-- that will eventually be sent to an external LLM. This script shows
-- how to protect that content on SAP HANA Cloud BEFORE it leaves the
-- SAP boundary, using the database's native security features against
-- a small financial-reporting context store.
--
-- It demonstrates five techniques, each on the same dataset:
--   1. Dynamic data masking      — hide identifying columns per privilege
--   2. K-anonymity               — generalize quasi-identifiers
--   3. L-diversity               — protect a sensitive structured attribute
--   4. Differential privacy      — add calibrated noise to numeric signals
--   5. Row-level security        — scope retrieval to a user's own rows
--
-- WHAT IS ACHIEVED
-- ----------------
-- After running the script, the same context store can be queried
-- through views that mask metadata, generalize department identity,
-- noise sensitive counts, and restrict rows by department — while a
-- vector-similarity retrieval query still returns useful, grounded
-- results. Structured columns are protected inside HANA; the free-text
-- body (an NCLOB) is protected separately at the PII-detection layer,
-- covered by the companion Python script.
--
-- PREREQUISITES
-- -------------
--   * SAP HANA Cloud instance with the Vector Engine enabled
--   * Data Privacy / anonymization features enabled
--   * Embedding model available: SAP_NEB.20240715
--   * Privilege to create tables, views, roles, and masks
--
-- HOW TO RUN
-- ----------
-- Run this file top to bottom in the SAP HANA database explorer SQL
-- console (or hdbsql / DBeaver) connected to your HANA Cloud instance.
-- No application server or external service is required for the SQL.
-- To see masking take effect, run the verification SELECTs as a user
-- WITHOUT the UNMASKED privilege on the table.
-- ============================================================


-- ============================================================
-- CONTEXT STORE AND SAMPLE DATA
-- ============================================================
-- Financial-reporting context store. RETRIEVAL_COUNT is DOUBLE so it
-- can serve as the sensitive column for differential privacy. Vectors
-- are generated in-database with VECTOR_EMBEDDING().

CREATE TABLE "FIN_REPORT_CONTEXT" (
    "ID"              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "DOC_ID"          NVARCHAR(40),
    "DOC_VERSION"     NVARCHAR(10),
    "FILING_TYPE"     NVARCHAR(40),
    "FISCAL_YEAR"     NVARCHAR(4),
    "DEPARTMENT"      NVARCHAR(40),
    "AUTHOR"          NVARCHAR(80),
    "SECTION"         NVARCHAR(60),
    "CHUNK_TEXT"      NCLOB,
    "CHUNK_VECTOR"    REAL_VECTOR(768),
    "RETRIEVAL_COUNT" DOUBLE,
    "IS_ACTIVE"       NVARCHAR(1) DEFAULT 'Y'
);

INSERT INTO "FIN_REPORT_CONTEXT"
    ("DOC_ID","DOC_VERSION","FILING_TYPE","FISCAL_YEAR","DEPARTMENT",
     "AUTHOR","SECTION","CHUNK_TEXT","CHUNK_VECTOR","RETRIEVAL_COUNT","IS_ACTIVE")
VALUES
('FR-Q4-2023','v1.0','Quarterly Report','2023','Finance',
 'Maria Steinberg','Results',
 'Revenue for Q4 2023 reached EUR 142.3 million, a 12% increase year-over-year. CFO Maria Steinberg noted that the EBITDA margin improved to 18.4%, driven by cost optimization in the EMEA region.',
 VECTOR_EMBEDDING('Revenue for Q4 2023 reached EUR 142.3 million, a 12% increase year-over-year. CFO Maria Steinberg noted that the EBITDA margin improved to 18.4%, driven by cost optimization in the EMEA region.','DOCUMENT','SAP_NEB.20240715'),
 34, 'Y'),
('FR-Q3-2023','v1.0','Quarterly Report','2023','Finance',
 'Maria Steinberg','Liquidity',
 'Free cash flow for Q3 2023 was EUR 58.1 million. The treasury team maintained EUR hedging coverage at 75% of forecast exposure, within the approved policy band.',
 VECTOR_EMBEDDING('Free cash flow for Q3 2023 was EUR 58.1 million. The treasury team maintained EUR hedging coverage at 75% of forecast exposure, within the approved policy band.','DOCUMENT','SAP_NEB.20240715'),
 21, 'Y'),
('CF-AML-2023','v2.0','Compliance Filing','2023','Compliance',
 'Daniel Okoro','AML Review',
 'The 2023 anti-money-laundering review identified three medium-risk findings in onboarding controls. Remediation owner Daniel Okoro confirmed closure of all items by 31 December 2023.',
 VECTOR_EMBEDDING('The 2023 anti-money-laundering review identified three medium-risk findings in onboarding controls. Remediation owner Daniel Okoro confirmed closure of all items by 31 December 2023.','DOCUMENT','SAP_NEB.20240715'),
 18, 'Y'),
('CF-SOX-2023','v1.0','Compliance Filing','2023','Compliance',
 'Daniel Okoro','SOX Controls',
 'SOX control testing covered 42 key controls across the revenue cycle. Two deficiencies were noted and downgraded to non-material after compensating controls were evidenced.',
 VECTOR_EMBEDDING('SOX control testing covered 42 key controls across the revenue cycle. Two deficiencies were noted and downgraded to non-material after compensating controls were evidenced.','DOCUMENT','SAP_NEB.20240715'),
 12, 'Y'),
('IA-RISK-2023','v3.0','Audit Opinion','2023','Internal Audit',
 'Priya Nair','Risk Register',
 'The internal audit risk register rating for FX exposure was revised from HIGH to MEDIUM effective 1 January 2024, reflecting the expanded hedging program approved by the board.',
 VECTOR_EMBEDDING('The internal audit risk register rating for FX exposure was revised from HIGH to MEDIUM effective 1 January 2024, reflecting the expanded hedging program approved by the board.','DOCUMENT','SAP_NEB.20240715'),
 27, 'Y'),
('IA-OPS-2023','v1.0','Audit Opinion','2023','Internal Audit',
 'Priya Nair','Operations',
 'The audit of procurement operations concluded with an overall satisfactory opinion. One observation regarding vendor master data quality was raised for management action.',
 VECTOR_EMBEDDING('The audit of procurement operations concluded with an overall satisfactory opinion. One observation regarding vendor master data quality was raised for management action.','DOCUMENT','SAP_NEB.20240715'),
 9, 'Y');


-- ============================================================
-- DYNAMIC DATA MASKING
-- ============================================================
-- Masks identifying columns so users without the UNMASKED privilege
-- see redacted values. Masking is applied at table level and is
-- inherited by every view over the table. HANA masks character
-- columns; the NCLOB text body is handled at the PII layer instead.

ALTER TABLE "FIN_REPORT_CONTEXT" ADD MASK ("DOC_ID" USING 'XXXX-MASKED');
ALTER TABLE "FIN_REPORT_CONTEXT" ADD MASK ("AUTHOR" USING 'REDACTED');

-- Verify as a user WITHOUT the UNMASKED privilege:
SELECT "ID", "DOC_ID", "AUTHOR", "DEPARTMENT",
       LEFT("CHUNK_TEXT", 80) AS "CHUNK_PREVIEW"
FROM "FIN_REPORT_CONTEXT";
-- DOC_ID and AUTHOR return masked values; the text body remains
-- visible, which is why the PII-detection layer complements masking.


-- ============================================================
-- K-ANONYMITY
-- ============================================================
-- Generalizes DEPARTMENT to 'Business' through an embedded hierarchy
-- so no single department value makes a record uniquely identifiable.

CREATE VIEW "FIN_REPORT_KANON" (
    "ID",
    "DEPARTMENT",
    "CHUNK_TEXT"
)
AS
SELECT
    "ID",
    "DEPARTMENT",
    "CHUNK_TEXT"
FROM "FIN_REPORT_CONTEXT"
WITH ANONYMIZATION (
    ALGORITHM 'K-ANONYMITY'
    PARAMETERS '{"k":2}'
    COLUMN "ID"
    PARAMETERS '{"is_sequence": true}'
    COLUMN "DEPARTMENT"
    PARAMETERS '{
        "is_quasi_identifier": true,
        "hierarchy": {
            "embedded": [
                ["Finance","Business"],
                ["Compliance","Business"],
                ["Internal Audit","Business"]
            ]
        }
    }'
);

REFRESH VIEW "FIN_REPORT_KANON" ANONYMIZATION;

SELECT "DEPARTMENT", LEFT("CHUNK_TEXT",80) AS "CHUNK_PREVIEW"
FROM "FIN_REPORT_KANON";
-- DEPARTMENT is generalized to 'Business' across all rows, so a chunk
-- can no longer be traced to a specific department.


-- ============================================================
-- L-DIVERSITY
-- ============================================================
-- Extends k-anonymity by requiring diversity in a sensitive structured
-- attribute (FILING_TYPE) within each equivalence class.

CREATE VIEW "FIN_REPORT_LDIV" (
    "ID",
    "DEPARTMENT",
    "FILING_TYPE"
)
AS
SELECT
    "ID",
    "DEPARTMENT",
    "FILING_TYPE"
FROM "FIN_REPORT_CONTEXT"
WITH ANONYMIZATION (
    ALGORITHM 'L-DIVERSITY'
    PARAMETERS '{"l":2}'
    COLUMN "ID"
    PARAMETERS '{"is_sequence": true}'
    COLUMN "DEPARTMENT"
    PARAMETERS '{
        "is_quasi_identifier": true,
        "hierarchy": {
            "embedded": [
                ["Finance","Business"],
                ["Compliance","Business"],
                ["Internal Audit","Business"]
            ]
        }
    }'
    COLUMN "FILING_TYPE"
    PARAMETERS '{"is_sensitive": true}'
);

REFRESH VIEW "FIN_REPORT_LDIV" ANONYMIZATION;

SELECT "DEPARTMENT", "FILING_TYPE" FROM "FIN_REPORT_LDIV";


-- ============================================================
-- DIFFERENTIAL PRIVACY
-- ============================================================
-- Adds calibrated noise to a numeric signal (retrieval frequency) so
-- individual values cannot be read off, while aggregate trends survive.

CREATE VIEW "FIN_REPORT_DP" (
    "ID",
    "RETRIEVAL_COUNT"
)
AS
SELECT
    "ID",
    "RETRIEVAL_COUNT"
FROM "FIN_REPORT_CONTEXT"
WITH ANONYMIZATION (
    ALGORITHM 'DIFFERENTIAL_PRIVACY'
    PARAMETERS ''
    COLUMN "ID"
    PARAMETERS '{"is_sequence": true}'
    COLUMN "RETRIEVAL_COUNT"
    PARAMETERS '{"is_sensitive": true, "epsilon": 0.5, "sensitivity": 50}'
);

REFRESH VIEW "FIN_REPORT_DP" ANONYMIZATION;

SELECT "RETRIEVAL_COUNT" FROM "FIN_REPORT_DP";
-- The noised output differs substantially from the true counts, so an
-- analyst cannot infer how often any one chunk is accessed. Department-
-- level trends remain usable; per-row values do not.


-- ============================================================
-- ROW-LEVEL SECURITY (RETRIEVAL-SHAPED)
-- ============================================================
-- Scopes retrieval to a department through a view. The vector search
-- runs against the view, so a user only ever retrieves their own
-- department's rows, however semantically similar other rows are.
-- The column masks still apply through the view.

CREATE ROLE COMPLIANCE_READER;

CREATE VIEW "FIN_REPORT_COMPLIANCE" AS
SELECT "ID", "DOC_ID", "AUTHOR", "SECTION", "CHUNK_TEXT", "CHUNK_VECTOR", "IS_ACTIVE"
FROM "FIN_REPORT_CONTEXT"
WHERE "DEPARTMENT" = 'Compliance';

GRANT SELECT ON "FIN_REPORT_COMPLIANCE" TO COMPLIANCE_READER;

-- A compliance user's retrieval query (bind the user's question to ?):
SELECT TOP 3
    "DOC_ID",
    "SECTION",
    "CHUNK_TEXT",
    COSINE_SIMILARITY("CHUNK_VECTOR",
        VECTOR_EMBEDDING(?, 'QUERY', 'SAP_NEB.20240715')
    ) AS "SCORE"
FROM "FIN_REPORT_COMPLIANCE"
WHERE "IS_ACTIVE" = 'Y'
ORDER BY "SCORE" DESC;

-- Finance counterpart, same pattern:
CREATE VIEW "FIN_REPORT_FINANCE" AS
SELECT "ID", "DOC_ID", "AUTHOR", "SECTION", "CHUNK_TEXT", "CHUNK_VECTOR", "IS_ACTIVE"
FROM "FIN_REPORT_CONTEXT"
WHERE "DEPARTMENT" = 'Finance';


-- ============================================================
-- TEXT-BODY PII DETECTION
-- ============================================================
-- The NCLOB text body is protected outside the database with a PII
-- detection and anonymization step before the context package is sent
-- to the LLM. See the companion Python script (presidio_pii_detection.py).
-- ============================================================
